### PR TITLE
Updating the documentation with new Azure Store certificate data

### PR DESCRIPTION
**Pull request by v-shresh**
This request is for updating the authentication certificate data for Azure store resource provider SDK.

### CODE REVIEW

**Comment by Dmitry-Me** [comment]
How about combining all of this into fewer commits? I can explain how this can be done.

**Comment by v-shresh** [comment]
Yes Sure. Let me know how to go about on this.

Thanks,
Shrey

**Comment by Dmitry-Me** [comment]
Okay, here we have ten commits and suppose you want to merge them into one. Here's how:
    git checkout master
    git reset HEAD~10 (this undoes the commits from your local repo and the changes get back into your working copy)

then you review the changes and commit all the changes as one commit and then...

    git push --force https://github.com/v-shresh/azure-resource-provider-sdk master

the latter replaces your ten commits with one in your remote repo

**Comment by v-shresh** [comment]
Done. can you check if that is okay.

**Pull request closed without merging**
