### PR TITLE
Broken Links & SSO data edit.

### PR DESCRIPTION
**Pull request by v-shresh**
Broken Links & SSO data edit.

### CODE REVIEW

**Comment by Dmitry-Me** [comment]
Yes, this is what happens when you try to do everything in master.

**Comment by v-shresh** [comment]
Shall we merge this now?

**Comment by Dmitry-Me** [comment]
What options do we have? You don't want to use branches and so we're guaranteed to have a messy history. I guess, yes, we'd better merge it and relax till September 2016 when Microsoft likely breaks Store integration once again.

**Comment by Dmitry-Me** [comment]
Oh, finally it's merged! Two months with outdated information on SSL certificates? Who cares! I'll close https://github.com/Azure/azure-resource-provider-sdk/issues/60 now.

**Pull request merged**
